version: '3.4'

networks:
  api-dev:
    driver: bridge 
    
volumes:
  db_volume:

services:
  api:
    image: api:latest
    build:
      context: Links.API
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - 5020:8080
    environment: 
     - ConnectionString=host=db;port=5432;database=linkdb;username=linkuser;password=linkuser
    networks:
      - api-dev

  db:
    image: postgres:latest
    ports:
     - 5430:5432
    restart: always
    volumes:
     - ./pg_init.sh:/docker-entrypoint-initdb.d/db.sh
     - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=linkuser
      - POSTGRES_PASSWORD=linkuser
      - SQL_DATABASE=linkdb
    networks:
      - api-dev
